YACLib: CalculatorService Class Reference
CalculatorService Class Reference
Public Member Functions
CalculatorService (yaclib::IExecutorPtr e)
yaclib::Future< int > Increment (int value)
yaclib::Future< int > Double (int value)
Detailed Description
Examples
simple.cpp.
Definition at line 102 of file simple.cpp.
Constructor & Destructor Documentation
CalculatorService()
CalculatorService::CalculatorService (yaclib::IExecutorPtr e) inline explicit
Definition at line 104 of file simple.cpp.
Member Function Documentation
Double()
yaclib::Future<int> CalculatorService::Double (int value) inline
Definition at line 113 of file simple.cpp.
References yaclib::Run().
Referenced by TEST().
Increment()
yaclib::Future<int> CalculatorService::Increment (int value) inline
Definition at line 107 of file simple.cpp.
References yaclib::Run().
Referenced by TEST().
The documentation for this class was generated from the following file:
test/example/async/simple.cpp