YACLib: yaclib::IExecutor Class Reference
yaclib::IExecutor Class Reference abstract
#include <executor.hpp>
Public Types
enum class Type {
Custom = 0 , ThreadPool , Serial , Inline ,
SingleThread
}
Public Member Functions
virtual Type Tag () const =0
Return type of this executor.
template<typename Functor , std::enable_if_t<!std::is_base_of_v< ITask, std::decay_t< Functor >>, int > = 0>
bool Execute (Functor &&functor)
Execute given functor for details.
virtual bool Execute (ITask &task) noexcept=0
Execute given task.
Public Member Functions inherited from yaclib::util::IRef
virtual void IncRef () noexcept=0
Increments reference counter.
virtual void DecRef () noexcept=0
Decrements reference counter.
virtual ~IRef ()=default
Detailed Description
Definition at line 8 of file executor.hpp.
Member Enumeration Documentation
Type
enum yaclib::IExecutor::Type strong
Enumerator
Custom
ThreadPool
Serial
Inline
SingleThread
Definition at line 15 of file executor.hpp.
Member Function Documentation
Execute() [1/2]
template<typename Functor , std::enable_if_t<!std::is_base_of_v< ITask, std::decay_t< Functor >>, int > = 0> bool yaclib::IExecutor::Execute (Functor && functor) inline
Execute given functor for details.
See also
Execute
This method creates ITask with one allocation and call Execute(ITask)
Parameters
functor task to execute
Returns
true if the task is accepted and scheduled for execution, false if the task is rejected
Definition at line 36 of file executor.hpp.
References yaclib::detail::MakeUniqueTask().
Referenced by yaclib::detail::BaseCore::Execute(), and yaclib::Run().
Execute() [2/2]
virtual bool yaclib::IExecutor::Execute (ITask & task) pure virtual noexcept
Execute given task.
This method may either accept or reject the task
This method always increments reference counter for the given task, even if it rejects the task after that. If the task is rejected, the reference counter is decremented back, otherwise the counter is decremented when the task is no longer needed by the executor.
Parameters
task task to execute
Returns
true if the task is accepted and scheduled for execution, false if the task is rejected
Tag()
virtual Type yaclib::IExecutor::Tag () const pure virtual
Return type of this executor.
Referenced by yaclib::Run().
The documentation for this class was generated from the following file:
include/yaclib/executor/executor.hpp