YACLib: yaclib::detail::BaseCore Class Reference
yaclib::detail::BaseCore Class Reference abstract
#include <base_core.hpp>
Public Types
enum class State {
Empty , HasResult , HasCallback , HasCallbackInline ,
HasWait , HasStop
}
Public Member Functions
BaseCore (State s) noexcept
State GetState () const noexcept
void SetState (State s) noexcept
IExecutorPtr GetExecutor () const noexcept
void SetExecutor (IExecutorPtr executor) noexcept
void SetCallback (util::Ptr< ITask > callback)
void SetCallbackInline (util::Ptr< ITask > callback)
bool SetWait (util::IRef &callback) noexcept
bool ResetWait () noexcept
Public Member Functions inherited from yaclib::util::IRef
virtual void IncRef () noexcept=0
Increments reference counter.
virtual void DecRef () noexcept=0
Decrements reference counter.
virtual ~IRef ()=default
Public Member Functions inherited from yaclib::util::detail::Node
void Link (Node *prev, Node *next) noexcept
bool IsLinked () const noexcept
Is node linked in circular list?
void Unlink () noexcept
Unlink this node from current list.
Protected Member Functions
void Execute () noexcept
void ExecuteInline () noexcept
void Clean () noexcept
void Call () noexcept override
virtual void CallInline (void *caller) noexcept=0
void Cancel () noexcept final
Protected Attributes
std::atomic< State > _state
util::Ptr< ITask > _caller
IExecutorPtr _executor {MakeInline()}
util::Ptr< IRef > _callback
Additional Inherited Members
Public Attributes inherited from yaclib::util::detail::Node
Node * _prev {this}
Node * _next {this}
Detailed Description
Definition at line 12 of file base_core.hpp.
Member Enumeration Documentation
State
enum yaclib::detail::BaseCore::State strong
Enumerator
Empty
HasResult
HasCallback
HasCallbackInline
HasWait
HasStop
Definition at line 14 of file base_core.hpp.
Constructor & Destructor Documentation
BaseCore()
yaclib::detail::BaseCore::BaseCore (State s) explicit noexcept
Definition at line 5 of file base_core.cpp.
Member Function Documentation
Call()
void yaclib::detail::BaseCore::Call () override protected virtual noexcept
Implements yaclib::util::IFunc.
Definition at line 69 of file base_core.cpp.
CallInline()
virtual void yaclib::detail::BaseCore::CallInline (void * caller) protected pure virtual noexcept
Implemented in yaclib::detail::AnyCombinator< T, P >, and yaclib::detail::AllCombinator< T, N, IsArray, FutureValue >.
Referenced by ExecuteInline().
Cancel()
void yaclib::detail::BaseCore::Cancel () final protected virtual noexcept
Implements yaclib::ITask.
Definition at line 72 of file base_core.cpp.
References _caller, and Clean().
Referenced by yaclib::detail::ResultCore< Value >::SetResult().
Clean()
void yaclib::detail::BaseCore::Clean () protected noexcept
Definition at line 77 of file base_core.cpp.
References _callback, and _executor.
Referenced by Cancel(), Execute(), and ExecuteInline().
Execute()
void yaclib::detail::BaseCore::Execute () protected noexcept
Definition at line 57 of file base_core.cpp.
References _caller, _executor, Clean(), and yaclib::IExecutor::Execute().
Referenced by SetCallback(), and yaclib::detail::ResultCore< Value >::SetResult().
ExecuteInline()
void yaclib::detail::BaseCore::ExecuteInline () protected noexcept
Definition at line 64 of file base_core.cpp.
References CallInline(), and Clean().
Referenced by SetCallbackInline(), and yaclib::detail::ResultCore< Value >::SetResult().
GetExecutor()
IExecutorPtr yaclib::detail::BaseCore::GetExecutor () const noexcept
Definition at line 8 of file base_core.cpp.
References _executor.
GetState()
BaseCore::State yaclib::detail::BaseCore::GetState () const noexcept
Definition at line 15 of file base_core.cpp.
References _state.
Referenced by yaclib::detail::AllCombinator< T, N, IsArray, FutureValue >::CallInline(), and yaclib::detail::AnyCombinator< T, P >::CallInline().
ResetWait()
bool yaclib::detail::BaseCore::ResetWait () noexcept
Definition at line 48 of file base_core.cpp.
References _callback, _state, Empty, and HasWait.
SetCallback()
void yaclib::detail::BaseCore::SetCallback (util::Ptr< ITask > callback)
Definition at line 22 of file base_core.cpp.
References _callback, _state, Execute(), HasCallback, and HasResult.
SetCallbackInline()
void yaclib::detail::BaseCore::SetCallbackInline (util::Ptr< ITask > callback)
Definition at line 29 of file base_core.cpp.
References _callback, _state, ExecuteInline(), HasCallbackInline, and HasResult.
SetExecutor()
void yaclib::detail::BaseCore::SetExecutor (IExecutorPtr executor) noexcept
Definition at line 11 of file base_core.cpp.
SetState()
void yaclib::detail::BaseCore::SetState (State s) noexcept
Definition at line 18 of file base_core.cpp.
SetWait()
bool yaclib::detail::BaseCore::SetWait (util::IRef & callback) noexcept
Definition at line 36 of file base_core.cpp.
Member Data Documentation
_callback
util::Ptr<IRef> yaclib::detail::BaseCore::_callback protected
Definition at line 40 of file base_core.hpp.
Referenced by Clean(), ResetWait(), SetCallback(), SetCallbackInline(), and yaclib::detail::ResultCore< Value >::SetResult().
_caller
util::Ptr<ITask> yaclib::detail::BaseCore::_caller protected
Definition at line 38 of file base_core.hpp.
Referenced by Cancel(), Execute(), and yaclib::detail::ResultCore< Value >::SetResult().
_executor
IExecutorPtr yaclib::detail::BaseCore::_executor {MakeInline()} protected
Definition at line 39 of file base_core.hpp.
Referenced by Clean(), Execute(), and GetExecutor().
_state
std::atomic<State> yaclib::detail::BaseCore::_state protected
Definition at line 37 of file base_core.hpp.
Referenced by GetState(), ResetWait(), SetCallback(), SetCallbackInline(), and yaclib::detail::ResultCore< Value >::SetResult().
The documentation for this class was generated from the following files:
include/yaclib/async/detail/base_core.hpp
src/async/base_core.cpp