YACLib: yaclib::util::Ptr< T > Class Template Reference
yaclib::util::Ptr< T > Class Template Reference
A intrusive pointer to objects with an embedded reference count.
#include <intrusive_ptr.hpp>
Public Member Functions
constexpr Ptr () noexcept
Ptr (T *other, bool acquire=true) noexcept
Ptr (Ptr &&other) noexcept
Ptr (const Ptr &other) noexcept
template<typename U >
Ptr (Ptr< U > &&other) noexcept
template<typename U >
Ptr (const Ptr< U > &other) noexcept
Ptr & operator= (T *other) noexcept
Ptr & operator= (Ptr &&other) noexcept
Ptr & operator= (const Ptr &other) noexcept
template<typename U >
Ptr & operator= (const Ptr< U > &other) noexcept
template<typename U >
Ptr & operator= (Ptr< U > &&other) noexcept
~Ptr ()
T * Get () const noexcept
T * Release ()
T & operator* () const noexcept
T * operator-> () const noexcept
operator bool () const noexcept
void Swap (Ptr &other) noexcept
Friends
template<typename U >
class Ptr
Detailed Description
template<typename T>
class yaclib::util::Ptr< T >
A intrusive pointer to objects with an embedded reference count.
https://www.boost.org/doc/libs/1_77_0/libs/smart_ptr/doc/html/smart_ptr.html#intrusive_ptr
Definition at line 17 of file intrusive_ptr.hpp.
Constructor & Destructor Documentation
Ptr() [1/6]
template<typename T > constexpr yaclib::util::Ptr< T >::Ptr () inline constexpr noexcept
Definition at line 21 of file intrusive_ptr.hpp.
Ptr() [2/6]
template<typename T > yaclib::util::Ptr< T >::Ptr (T * other, bool acquire = true) inline noexcept
Definition at line 24 of file intrusive_ptr.hpp.
Ptr() [3/6]
template<typename T > yaclib::util::Ptr< T >::Ptr (Ptr< T > && other) inline noexcept
Definition at line 29 of file intrusive_ptr.hpp.
Ptr() [4/6]
template<typename T > yaclib::util::Ptr< T >::Ptr (const Ptr< T > & other) inline noexcept
Definition at line 31 of file intrusive_ptr.hpp.
Ptr() [5/6]
template<typename T > template<typename U > yaclib::util::Ptr< T >::Ptr (Ptr< U > && other) inline noexcept
Definition at line 37 of file intrusive_ptr.hpp.
Ptr() [6/6]
template<typename T > template<typename U > yaclib::util::Ptr< T >::Ptr (const Ptr< U > & other) inline noexcept
Definition at line 40 of file intrusive_ptr.hpp.
~Ptr()
template<typename T > yaclib::util::Ptr< T >::~Ptr () inline
Definition at line 69 of file intrusive_ptr.hpp.
Member Function Documentation
Get()
template<typename T > T* yaclib::util::Ptr< T >::Get () const inline noexcept
Definition at line 75 of file intrusive_ptr.hpp.
operator bool()
template<typename T > yaclib::util::Ptr< T >::operator bool () const inline explicit noexcept
Definition at line 93 of file intrusive_ptr.hpp.
operator*()
template<typename T > T& yaclib::util::Ptr< T >::operator* () const inline noexcept
Definition at line 83 of file intrusive_ptr.hpp.
operator->()
template<typename T > T* yaclib::util::Ptr< T >::operator-> () const inline noexcept
Definition at line 88 of file intrusive_ptr.hpp.
operator=() [1/5]
template<typename T > Ptr& yaclib::util::Ptr< T >::operator= (const Ptr< T > & other) inline noexcept
Definition at line 54 of file intrusive_ptr.hpp.
References yaclib::util::Ptr< T >::Swap().
operator=() [2/5]
template<typename T > template<typename U > Ptr& yaclib::util::Ptr< T >::operator= (const Ptr< U > & other) inline noexcept
Definition at line 59 of file intrusive_ptr.hpp.
References yaclib::util::Ptr< T >::Swap().
operator=() [3/5]
template<typename T > Ptr& yaclib::util::Ptr< T >::operator= (Ptr< T > && other) inline noexcept
Definition at line 50 of file intrusive_ptr.hpp.
References yaclib::util::Ptr< T >::Swap().
operator=() [4/5]
template<typename T > template<typename U > Ptr& yaclib::util::Ptr< T >::operator= (Ptr< U > && other) inline noexcept
Definition at line 64 of file intrusive_ptr.hpp.
References yaclib::util::Ptr< T >::Swap().
operator=() [5/5]
template<typename T > Ptr& yaclib::util::Ptr< T >::operator= (T * other) inline noexcept
Definition at line 46 of file intrusive_ptr.hpp.
References yaclib::util::Ptr< T >::Swap().
Release()
template<typename T > T* yaclib::util::Ptr< T >::Release () inline
Definition at line 79 of file intrusive_ptr.hpp.
Swap()
template<typename T > void yaclib::util::Ptr< T >::Swap (Ptr< T > & other) inline noexcept
Definition at line 97 of file intrusive_ptr.hpp.
Referenced by yaclib::util::Ptr< T >::operator=().
Friends And Related Function Documentation
Ptr
template<typename T > template<typename U > friend class Ptr friend
Definition at line 105 of file intrusive_ptr.hpp.
The documentation for this class was generated from the following file:
include/yaclib/util/intrusive_ptr.hpp