YACLib: yaclib::detail::ResultCore< Value > Class Template Reference
yaclib::detail::ResultCore< Value > Class Template Reference
#include <result_core.hpp>
Public Member Functions
ResultCore () noexcept
template<typename T >
ResultCore (T &&value)
void SetResult (util::Result< Value > &&result) noexcept
util::Result< Value > & Get () noexcept
Public Member Functions inherited from yaclib::detail::BaseCore
BaseCore (State s) noexcept
State GetState () const noexcept
void SetState (State s) noexcept
IExecutorPtr GetExecutor () const noexcept
void SetExecutor (IExecutorPtr executor) noexcept
void SetCallback (util::Ptr< ITask > callback)
void SetCallbackInline (util::Ptr< ITask > callback)
bool SetWait (util::IRef &callback) noexcept
bool ResetWait () noexcept
Public Member Functions inherited from yaclib::util::IRef
virtual void IncRef () noexcept=0
Increments reference counter.
virtual void DecRef () noexcept=0
Decrements reference counter.
virtual ~IRef ()=default
Public Member Functions inherited from yaclib::util::detail::Node
void Link (Node *prev, Node *next) noexcept
bool IsLinked () const noexcept
Is node linked in circular list?
void Unlink () noexcept
Unlink this node from current list.
Additional Inherited Members
Public Types inherited from yaclib::detail::BaseCore
enum class State {
Empty , HasResult , HasCallback , HasCallbackInline ,
HasWait , HasStop
}
Public Attributes inherited from yaclib::util::detail::Node
Node * _prev {this}
Node * _next {this}
Protected Member Functions inherited from yaclib::detail::BaseCore
void Execute () noexcept
void ExecuteInline () noexcept
void Clean () noexcept
void Call () noexcept override
void Cancel () noexcept final
Protected Attributes inherited from yaclib::detail::BaseCore
std::atomic< State > _state
util::Ptr< ITask > _caller
IExecutorPtr _executor {MakeInline()}
util::Ptr< IRef > _callback
Detailed Description
template<typename Value>
class yaclib::detail::ResultCore< Value >
Definition at line 9 of file result_core.hpp.
Constructor & Destructor Documentation
ResultCore() [1/2]
template<typename Value > yaclib::detail::ResultCore< Value >::ResultCore () inline noexcept
Definition at line 11 of file result_core.hpp.
References yaclib::detail::BaseCore::Empty.
ResultCore() [2/2]
template<typename Value > template<typename T > yaclib::detail::ResultCore< Value >::ResultCore (T && value) inline explicit
Definition at line 15 of file result_core.hpp.
Member Function Documentation
Get()
template<typename Value > util::Result<Value>& yaclib::detail::ResultCore< Value >::Get () inline noexcept
Definition at line 40 of file result_core.hpp.
SetResult()
template<typename Value > void yaclib::detail::ResultCore< Value >::SetResult (util::Result< Value > && result) inline noexcept
Definition at line 18 of file result_core.hpp.
References yaclib::detail::BaseCore::_callback, yaclib::detail::BaseCore::_caller, yaclib::detail::BaseCore::_state, yaclib::detail::BaseCore::Cancel(), yaclib::detail::BaseCore::Execute(), yaclib::detail::BaseCore::ExecuteInline(), yaclib::detail::BaseCore::HasCallback, yaclib::detail::BaseCore::HasCallbackInline, yaclib::detail::BaseCore::HasResult, yaclib::detail::BaseCore::HasStop, and yaclib::detail::BaseCore::HasWait.
The documentation for this class was generated from the following file:
include/yaclib/async/detail/result_core.hpp