YACLib: yaclib::util::Result< T > Class Template Reference
yaclib::util::Result< T > Class Template Reference
Encapsulated return value from caller.
#include <result.hpp>
Public Member Functions
Result ()
Result (Result &&other) noexcept(std::is_nothrow_move_constructible_v< VariantT >)
Result & operator= (Result &&other) noexcept(std::is_nothrow_move_assignable_v< VariantT >)
Result (const Result &other)=delete
Result & operator= (const Result &other)=delete
template<typename U >
Result (U &&result)
template<typename U >
void Set (U &&result)
operator bool () const noexcept
T Ok () &&
ResultState State () const noexcept
T Value () &&noexcept
std::error_code Error () &&noexcept
std::exception_ptr Exception () &&noexcept
Static Public Member Functions
static Result Default ()
Detailed Description
template<typename T>
class yaclib::util::Result< T >
Encapsulated return value from caller.
Template Parameters
T type to store in Result
Examples
simple.cpp.
Definition at line 66 of file result.hpp.
Constructor & Destructor Documentation
Result() [1/4]
template<typename T > yaclib::util::Result< T >::Result () inline
Definition at line 87 of file result.hpp.
Result() [2/4]
template<typename T > yaclib::util::Result< T >::Result (Result< T > && other) inline noexcept
Definition at line 90 of file result.hpp.
Result() [3/4]
template<typename T > yaclib::util::Result< T >::Result (const Result< T > & other) delete
Result() [4/4]
template<typename T > template<typename U > yaclib::util::Result< T >::Result (U && result) inline
Definition at line 102 of file result.hpp.
Member Function Documentation
Default()
template<typename T > static Result yaclib::util::Result< T >::Default () inline static
Definition at line 82 of file result.hpp.
Referenced by yaclib::MakeFuture(), and yaclib::detail::AsyncInvoke< U, FunctorT, T >::Wrapper().
Error()
template<typename T > std::error_code yaclib::util::Result< T >::Error () && inline noexcept
Definition at line 153 of file result.hpp.
Exception()
template<typename T > std::exception_ptr yaclib::util::Result< T >::Exception () && inline noexcept
Definition at line 157 of file result.hpp.
Ok()
template<typename T > T yaclib::util::Result< T >::Ok () && inline
Definition at line 114 of file result.hpp.
References yaclib::util::Empty, yaclib::util::Error, yaclib::util::Exception, yaclib::util::Result< T >::State(), and yaclib::util::Value.
operator bool()
template<typename T > yaclib::util::Result< T >::operator bool () const inline explicit noexcept
Definition at line 110 of file result.hpp.
References yaclib::util::Result< T >::State(), and yaclib::util::Value.
operator=() [1/2]
template<typename T > Result& yaclib::util::Result< T >::operator= (const Result< T > & other) delete
operator=() [2/2]
template<typename T > Result& yaclib::util::Result< T >::operator= (Result< T > && other) inline noexcept
Definition at line 93 of file result.hpp.
Set()
template<typename T > template<typename U > void yaclib::util::Result< T >::Set (U && result) inline
Definition at line 106 of file result.hpp.
State()
template<typename T > ResultState yaclib::util::Result< T >::State () const inline noexcept
Definition at line 135 of file result.hpp.
References yaclib::util::Empty, yaclib::util::Error, yaclib::util::Exception, and yaclib::util::Value.
Referenced by yaclib::util::Result< T >::Ok(), and yaclib::util::Result< T >::operator bool().
Value()
template<typename T > T yaclib::util::Result< T >::Value () && inline noexcept
Definition at line 147 of file result.hpp.
The documentation for this class was generated from the following file:
include/yaclib/util/result.hpp