YACLib: yaclib Namespace Reference
yaclib Namespace Reference
Namespaces
detail
util
Classes
class WaitGroup
class Future
Provides a mechanism to access the result of async operations.
class Promise
struct Contract
Describes channel with future and promise.
class IExecutor
class ITask
Callable that can be executed in an IExecutor.
class IThread
class IThreadFactory
class IThreadPool
Interface for thread-pool-like executors.
class Inline
Typedefs
using IExecutorPtr = util::Ptr< IExecutor >
using IThreadPtr = IThread *
using IThreadFactoryPtr = util::Ptr< IThreadFactory >
using IThreadPoolPtr = util::Ptr< IThreadPool >
Enumerations
enum class PolicyWhenAny { FirstError , LastError }
Functions
template<typename... Futures>
void Wait (Futures &&... fs)
Wait until Ready becomes true.
template<typename Rep , typename Period , typename... Futures>
bool WaitFor (const std::chrono::duration< Rep, Period > &timeout_duration, Futures &&... fs)
Wait until the specified timeout duration has elapsed or Ready becomes true.
template<typename Clock , typename Duration , typename... Futures>
bool WaitUntil (const std::chrono::time_point< Clock, Duration > &timeout_time, Futures &&... fs)
Wait until specified time has been reached or Ready becomes true.
template<typename It , typename T = util::detail::FutureValueT<typename std::iterator_traits<It>::value_type>>
auto WhenAll (It begin, size_t size)
Create Future which will be ready when all futures are ready.
template<typename It >
auto WhenAll (It begin, It end)
Create Future which will be ready when all futures are ready.
template<typename T , typename... Fs>
auto WhenAll (Future< T > &&head, Fs &&... tail)
Create Future which will be ready when all futures are ready.
template<PolicyWhenAny P = PolicyWhenAny::FirstError, typename It , typename T = util::detail::FutureValueT<typename std::iterator_traits<It>::value_type>>
auto WhenAny (It begin, size_t size)
Create Future that is ready when any of futures is ready.
template<PolicyWhenAny P = PolicyWhenAny::FirstError, typename It , typename T = util::detail::FutureValueT<typename std::iterator_traits<It>::value_type>>
auto WhenAny (It begin, It end)
Create Future that is ready when any of futures is ready.
template<PolicyWhenAny P = PolicyWhenAny::FirstError, typename T , typename... Fs>
auto WhenAny (Future< T > &&head, Fs &&... tail)
Create Future that is ready when any of futures is ready.
template<typename T >
Contract< T > MakeContract ()
Creates related future and promise.
Future< void > MakeFuture ()
template<typename V , typename T = std::remove_reference_t<V>>
Future< T > MakeFuture (V &&value)
template<typename T , typename V >
std::enable_if_t<!std::is_same_v< T, std::remove_reference_t< V > >, Future< T > > MakeFuture (V &&value)
template<typename Functor >
auto Run (const IExecutorPtr &e, Functor &&f)
Execute Callable functor via executor.
IExecutorPtr MakeInline () noexcept
Get Inline executor singleton object.
IExecutorPtr MakeSerial (IExecutorPtr e)
Serial is the asynchronous analogue of a mutex.
IThreadFactoryPtr MakeThreadFactory (size_t cache=0)
IThreadFactoryPtr MakeThreadFactory (IThreadFactoryPtr base, std::string name)
IThreadFactoryPtr MakeThreadFactory (IThreadFactoryPtr base, size_t priority)
IThreadFactoryPtr MakeThreadFactory (IThreadFactoryPtr base, util::IFuncPtr acquire, util::IFuncPtr release)
IThreadPool * CurrentThreadPool () noexcept
IThreadPoolPtr MakeThreadPool (size_t threads=std::thread::hardware_concurrency(), IThreadFactoryPtr tf=MakeThreadFactory())
Create new ThreadPool object.
Typedef Documentation
IExecutorPtr
using yaclib::IExecutorPtr = typedef util::Ptr<IExecutor>
Definition at line 53 of file executor.hpp.
IThreadFactoryPtr
using yaclib::IThreadFactoryPtr = typedef util::Ptr<IThreadFactory>
Definition at line 25 of file thread_factory.hpp.
IThreadPoolPtr
using yaclib::IThreadPoolPtr = typedef util::Ptr<IThreadPool>
Definition at line 41 of file thread_pool.hpp.
IThreadPtr
using yaclib::IThreadPtr = typedef IThread*
Definition at line 16 of file thread_factory.hpp.
Enumeration Type Documentation
PolicyWhenAny
enum yaclib::PolicyWhenAny strong
Enumerator
FirstError
LastError
Definition at line 12 of file when_any.hpp.
Function Documentation
CurrentThreadPool()
IThreadPool * yaclib::CurrentThreadPool () noexcept
Returns
Thread local pointer to the ThreadPool that owns the current thread nullptr if no ThreadPool owns the thread
Definition at line 261 of file thread_pool.cpp.
MakeContract()
template<typename T > Contract< T > yaclib::MakeContract ()
Creates related future and promise.
Returns
See also
Contract object with new future and promise
Definition at line 40 of file promise_impl.hpp.
References yaclib::Promise< T >::MakeFuture().
MakeFuture() [1/3]
Future< void > yaclib::MakeFuture ()
Definition at line 7 of file future_impl.cpp.
References yaclib::util::Result< T >::Default().
MakeFuture() [2/3]
template<typename V , typename T = std::remove_reference_t<V>> Future<T> yaclib::MakeFuture (V && value)
Definition at line 178 of file future.hpp.
MakeFuture() [3/3]
template<typename T , typename V > std::enable_if_t<!std::is_same_v<T, std::remove_reference_t<V> >, Future<T> > yaclib::MakeFuture (V && value)
Definition at line 183 of file future.hpp.
MakeInline()
IExecutorPtr yaclib::MakeInline () noexcept
Get Inline executor singleton object.
This executor immediately executes given Callable object in the same OS thread without any overhead.
Note
This object is useful as safe default executor value. See example.
auto task = [] { return 0; };
// Without inline executor:
IExecutorPtr executor = nullptr;
if (...) {
  executor = MakeThreadPool(4);
}
if (executor) {
  executor->Execute(task);
} else {
  a();
}
// With inline executor:
IExecutorPtr executor{MakeInlineExecutor()};
...
executor->Execute(task);
Definition at line 22 of file inline.cpp.
MakeSerial()
IExecutorPtr yaclib::MakeSerial (IExecutorPtr e)
Serial is the asynchronous analogue of a mutex.
It guarantees that the tasks scheduled for it will be executed strictly sequentially. Serial itself does not have its own threads, it decorates another executor and uses it to run its tasks.
Parameters
e executor to decorate
Returns
pointer to new Serial instance
Examples
serial.cpp, and simple.cpp.
Definition at line 73 of file serial.cpp.
Referenced by TEST().
MakeThreadFactory() [1/4]
IThreadFactoryPtr yaclib::MakeThreadFactory (IThreadFactoryPtr base, size_t priority)
Definition at line 348 of file thread_factory.cpp.
MakeThreadFactory() [2/4]
IThreadFactoryPtr yaclib::MakeThreadFactory (IThreadFactoryPtr base, std::string name)
Definition at line 352 of file thread_factory.cpp.
MakeThreadFactory() [3/4]
IThreadFactoryPtr yaclib::MakeThreadFactory (IThreadFactoryPtr base, util::IFuncPtr acquire, util::IFuncPtr release)
Definition at line 356 of file thread_factory.cpp.
MakeThreadFactory() [4/4]
IThreadFactoryPtr yaclib::MakeThreadFactory (size_t cache = 0)
Definition at line 340 of file thread_factory.cpp.
MakeThreadPool()
IThreadPoolPtr yaclib::MakeThreadPool (size_t threads = std::thread::hardware_concurrency(), IThreadFactoryPtr tf = MakeThreadFactory())
Create new ThreadPool object.
Parameters
threads the number of threads to create for this ThreadPool
f thread factory to use for thread creation.
See also
IThreadFactory
Returns
intrusive pointer to the new ThreadPool
Examples
serial.cpp, simple.cpp, thread_pool.cpp, when_all.cpp, and when_any.cpp.
Definition at line 265 of file thread_pool.cpp.
Referenced by TEST().
Run()
template<typename Functor > auto yaclib::Run (const IExecutorPtr & e, Functor && f)
Execute Callable functor via executor.
Parameters
e executor to be used to execute f and saved as callback executor for return Future
f functor to execute
Returns
Future corresponding f return value
Examples
simple.cpp, when_all.cpp, and when_any.cpp.
Definition at line 18 of file run.hpp.
References yaclib::IExecutor::Execute(), yaclib::IExecutor::Inline, and yaclib::IExecutor::Tag().
Referenced by CalculatorService::Double(), CalculatorService::Increment(), and TEST().
Wait()
template<typename... Futures> void yaclib::Wait (Futures &&... fs)
Wait until Ready becomes true.
Parameters
fs one or more futures to wait
Definition at line 13 of file wait.hpp.
References yaclib::detail::Wait().
WaitFor()
template<typename Rep , typename Period , typename... Futures> bool yaclib::WaitFor (const std::chrono::duration< Rep, Period > & timeout_duration, Futures &&... fs)
Wait until the specified timeout duration has elapsed or Ready becomes true.
The behavior is undefined if Valid is false before the call to this function. This function may block for longer than timeout_duration due to scheduling or resource contention delays.
Parameters
timeout_duration maximum duration to block for
fs futures to wait
Returns
The result of Ready upon exiting
Definition at line 17 of file wait_for.hpp.
References yaclib::detail::Wait().
WaitUntil()
template<typename Clock , typename Duration , typename... Futures> bool yaclib::WaitUntil (const std::chrono::time_point< Clock, Duration > & timeout_time, Futures &&... fs)
Wait until specified time has been reached or Ready becomes true.
The behavior is undefined if Valid is false before the call to this function. This function may block for longer than until after timeout_time has been reached due to scheduling or resource contention delays.
Parameters
timeout_time maximum time point to block until
fs futures to wait
Returns
The result of Ready upon exiting
Definition at line 18 of file wait_until.hpp.
References yaclib::detail::Wait().
WhenAll() [1/3]
template<typename T , typename... Fs> auto yaclib::WhenAll (Future< T > && head, Fs &&... tail)
Create Future which will be ready when all futures are ready.
Template Parameters
T type of all passed futures
Parameters
head,tail one or more futures to combine
Returns
Future<array<T>>
Definition at line 153 of file when_all.hpp.
References yaclib::detail::WhenAllImpl().
WhenAll() [2/3]
template<typename It > auto yaclib::WhenAll (It begin, It end)
Create Future which will be ready when all futures are ready.
Template Parameters
It type of passed iterator
T type of all passed futures
Parameters
begin,end the range of futures to combine
Returns
Future<vector<T>>
Definition at line 140 of file when_all.hpp.
References yaclib::util::IsFutureV, and WhenAll().
WhenAll() [3/3]
template<typename It , typename T = util::detail::FutureValueT<typename std::iterator_traits<It>::value_type>> auto yaclib::WhenAll (It begin, size_t size)
Create Future which will be ready when all futures are ready.
Template Parameters
It type of passed iterator
T type of all passed futures
Parameters
begin,size the range of futures to combine
Returns
Future<vector<T>>
Examples
when_all.cpp.
Definition at line 121 of file when_all.hpp.
References yaclib::detail::AllCombinator< T, N, IsArray, FutureValue >::Make().
Referenced by TEST(), and WhenAll().
WhenAny() [1/3]
template<PolicyWhenAny P = PolicyWhenAny::FirstError, typename T , typename... Fs> auto yaclib::WhenAny (Future< T > && head, Fs &&... tail)
Create Future that is ready when any of futures is ready.
Template Parameters
P policy WhenAny errors
T type of all passed futures
Parameters
head,tail one or more futures to combine
Returns
Future<T>
Definition at line 177 of file when_any.hpp.
References yaclib::detail::AnyCombinator< T, P >::Make().
WhenAny() [2/3]
template<PolicyWhenAny P = PolicyWhenAny::FirstError, typename It , typename T = util::detail::FutureValueT<typename std::iterator_traits<It>::value_type>> auto yaclib::WhenAny (It begin, It end)
Create Future that is ready when any of futures is ready.
Template Parameters
P policy WhenAny errors
It type of passed iterator
T type of all passed futures
Parameters
begin,end the range of futures to combine
Returns
Future<T>
Definition at line 164 of file when_any.hpp.
References yaclib::detail::WhenAnyImpl().
WhenAny() [3/3]
template<PolicyWhenAny P = PolicyWhenAny::FirstError, typename It , typename T = util::detail::FutureValueT<typename std::iterator_traits<It>::value_type>> auto yaclib::WhenAny (It begin, size_t size)
Create Future that is ready when any of futures is ready.
Template Parameters
P policy WhenAny errors
It type of passed iterator
T type of all passed futures
Parameters
begin,size the range of futures to combine
Returns
Future<T>
Examples
when_any.cpp.
Definition at line 149 of file when_any.hpp.
References yaclib::detail::WhenAnyImpl().
Referenced by TEST().