YACLib: yaclib::detail Namespace Reference
yaclib::detail Namespace Reference
Classes
struct NoTimeoutTag
class AllCombinatorBase
class AllCombinatorBase< void >
class AllCombinator
class AnyCombinatorBase
class AnyCombinatorBase< T, PolicyWhenAny::FirstError >
class AnyCombinator
class BaseCore
class Core
struct Return
struct Return< T, Functor, 1 >
struct Return< T, Functor, 2 >
struct Return< T, Functor, 4 >
struct Return< T, Functor, 8 >
class SyncInvoke
class AsyncInvoke
class ResultCore
class WaitCore
struct WaitCoreDeleter
class UniqueTask
Typedefs
template<typename T , PolicyWhenAny P>
using AnyCombinatorPtr = util::Ptr< AnyCombinator< T, P > >
template<typename Value >
using FutureCorePtr = util::Ptr< ResultCore< Value > >
template<typename Value >
using PromiseCorePtr = util::Ptr< ResultCore< Value > >
Functions
template<typename Timeout , typename... Cores>
bool Wait (const Timeout &t, Cores &... cs)
template bool Wait< NoTimeoutTag, BaseCore > (const NoTimeoutTag &, BaseCore &)
template<size_t N, typename T , typename... Fs>
void WhenAllImpl (util::Ptr< AllCombinator< T, N >> &combinator, Future< T > &&head, Fs &&... tail)
template<PolicyWhenAny P = PolicyWhenAny::FirstError, typename T , typename... Fs>
void WhenAnyImpl (detail::AnyCombinatorPtr< T, P > &combinator, Future< T > &&head, Fs &&... tail)
template<PolicyWhenAny P = PolicyWhenAny::FirstError, typename It , typename T = util::detail::FutureValueT<typename std::iterator_traits<It>::value_type>, typename Indx >
auto WhenAnyImpl (It iter, Indx begin, Indx end)
template<typename T , typename Functor >
constexpr int Tag ()
template<bool Inline, typename Ret , typename Arg , typename Functor >
auto SetSyncCallback (FutureCorePtr< Arg > caller, Functor &&f)
template<bool Inline, typename Ret , typename Arg , typename Functor >
auto SetAsyncCallback (FutureCorePtr< Arg > caller, Functor &&f)
template<bool Subscribe, bool Inline, typename Arg , typename Functor >
auto SetCallback (FutureCorePtr< Arg > caller, Functor &&f)
template<typename Functor >
ITask * MakeUniqueTask (Functor &&functor)
Typedef Documentation
AnyCombinatorPtr
template<typename T , PolicyWhenAny P> using yaclib::detail::AnyCombinatorPtr = typedef util::Ptr<AnyCombinator<T, P> >
Definition at line 103 of file when_any.hpp.
FutureCorePtr
template<typename Value > using yaclib::detail::FutureCorePtr = typedef util::Ptr<ResultCore<Value> >
Definition at line 11 of file future.hpp.
PromiseCorePtr
template<typename Value > using yaclib::detail::PromiseCorePtr = typedef util::Ptr<ResultCore<Value> >
Definition at line 10 of file promise.hpp.
Function Documentation
MakeUniqueTask()
template<typename Functor > ITask* yaclib::detail::MakeUniqueTask (Functor && functor)
Definition at line 36 of file task.hpp.
Referenced by yaclib::IExecutor::Execute().
SetAsyncCallback()
template<bool Inline, typename Ret , typename Arg , typename Functor > auto yaclib::detail::SetAsyncCallback (FutureCorePtr< Arg > caller, Functor && f)
Definition at line 218 of file future_impl.hpp.
SetCallback()
template<bool Subscribe, bool Inline, typename Arg , typename Functor > auto yaclib::detail::SetCallback (FutureCorePtr< Arg > caller, Functor && f)
Definition at line 234 of file future_impl.hpp.
SetSyncCallback()
template<bool Inline, typename Ret , typename Arg , typename Functor > auto yaclib::detail::SetSyncCallback (FutureCorePtr< Arg > caller, Functor && f)
Definition at line 204 of file future_impl.hpp.
Tag()
template<typename T , typename Functor > constexpr int yaclib::detail::Tag () constexpr
Definition at line 16 of file future_impl.hpp.
References yaclib::util::IsInvocableV.
Wait()
template<typename Timeout , typename... Cores> bool yaclib::detail::Wait (const Timeout & t, Cores &... cs)
Definition at line 13 of file wait_impl.hpp.
References yaclib::util::Counter< CounterBase, Deleter >::DecRef(), and yaclib::util::Counter< CounterBase, Deleter >::IncRef().
Referenced by yaclib::Wait(), yaclib::WaitFor(), and yaclib::WaitUntil().
Wait< NoTimeoutTag, BaseCore >()
template bool yaclib::detail::Wait< NoTimeoutTag, BaseCore > (const NoTimeoutTag & , BaseCore &)
WhenAllImpl()
template<size_t N, typename T , typename... Fs> void yaclib::detail::WhenAllImpl (util::Ptr< AllCombinator< T, N >> & combinator, Future< T > && head, Fs &&... tail)
Definition at line 102 of file when_all.hpp.
Referenced by yaclib::WhenAll().
WhenAnyImpl() [1/2]
template<PolicyWhenAny P = PolicyWhenAny::FirstError, typename T , typename... Fs> void yaclib::detail::WhenAnyImpl (detail::AnyCombinatorPtr< T, P > & combinator, Future< T > && head, Fs &&... tail)
Definition at line 106 of file when_any.hpp.
Referenced by yaclib::WhenAny().
WhenAnyImpl() [2/2]
template<PolicyWhenAny P = PolicyWhenAny::FirstError, typename It , typename T = util::detail::FutureValueT<typename std::iterator_traits<It>::value_type>, typename Indx > auto yaclib::detail::WhenAnyImpl (It iter, Indx begin, Indx end)
Definition at line 116 of file when_any.hpp.
References yaclib::FirstError, and yaclib::detail::AnyCombinator< T, P >::Make().