YACLib: test/example/async/simple.cpp File Reference
simple.cpp File Reference
#include <yaclib/async/run.hpp>
#include <yaclib/executor/executor.hpp>
#include <yaclib/executor/serial.hpp>
#include <yaclib/executor/thread_pool.hpp>
#include <atomic>
#include <iostream>
#include <gtest/gtest.h>
Classes
class CalculatorService
Functions
TEST (Example, HelloWorld)
TEST (Example, Subscribe)
TEST (Example, Then)
TEST (Example, Pipeline)
TEST (Example, AsyncPipeline)
TEST (Example, Race)
TEST (Example, Serial)
Function Documentation
TEST() [1/7]
TEST (Example , AsyncPipeline)
Definition at line 123 of file simple.cpp.
References CalculatorService::Double(), CalculatorService::Increment(), and yaclib::MakeThreadPool().
TEST() [2/7]
TEST (Example , HelloWorld)
Examples
simple.cpp.
Definition at line 18 of file simple.cpp.
TEST() [3/7]
TEST (Example , Pipeline)
Definition at line 70 of file simple.cpp.
References yaclib::MakeThreadPool(), and yaclib::Run().
TEST() [4/7]
TEST (Example , Race)
Todo:
Add WhenAny example
Definition at line 147 of file simple.cpp.
References yaclib::MakeThreadPool(), and yaclib::Run().
TEST() [5/7]
TEST (Example , Serial)
Definition at line 167 of file simple.cpp.
References yaclib::MakeSerial(), yaclib::MakeThreadPool(), and yaclib::Run().
TEST() [6/7]
TEST (Example , Subscribe)
Definition at line 30 of file simple.cpp.
References yaclib::MakeThreadPool(), and yaclib::Run().
TEST() [7/7]
TEST (Example , Then)
Definition at line 47 of file simple.cpp.
References yaclib::MakeThreadPool(), yaclib::Run(), yaclib::Future< T >::Then(), and yaclib::Future< T >::Valid().